# Challenge 2 — Who is Compromised?

## Data Profiling

**Objective:** Understand the structure, size, coverage, and basic characteristics of the three supplied datasets before performing security analysis.

### Datasets
- `web_activity.csv` — endpoint internet activity
- `endpoint_security.csv` — antivirus, quarantine, and web-filter events
- `usb_events.csv` — USB device events

We will not modify the original datasets.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [2]:
from pathlib import Path

DATA_DIR = Path("../data")

print("Data directory:", DATA_DIR.resolve())

Data directory: C:\Users\Asus\Desktop\web_activity\data

In [3]:
web = pd.read_csv(DATA_DIR / "web_activity.csv")
security = pd.read_csv(DATA_DIR / "endpoint_security.csv")
usb = pd.read_csv(DATA_DIR / "usb_events.csv")

print("All datasets loaded.")

All datasets loaded.

In [4]:
print("Web activity:", web.shape)
print("Endpoint security:", security.shape)
print("USB events:", usb.shape)

Web activity: (2812118, 8)
Endpoint security: (23540, 8)
USB events: (8, 8)

In [5]:
print("WEB ACTIVITY")
print(web.columns.tolist())

print("\nENDPOINT SECURITY")
print(security.columns.tolist())

print("\nUSB EVENTS")
print(usb.columns.tolist())

WEB ACTIVITY
['endpoint_id', 'endpoint_name', 'mac', 'unit', 'log_type', 'event_time', 'received_time', 'message']

ENDPOINT SECURITY
['endpoint_id', 'endpoint_name', 'mac', 'unit', 'log_type', 'event_time', 'received_time', 'message']

USB EVENTS
['endpoint_id', 'endpoint_name', 'mac', 'unit', 'log_type', 'event_time', 'received_time', 'message']

In [17]:
display(web.head(10))

,endpoint_id,endpoint_name,mac,unit,log_type,event_time,received_time,message
0,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,192.178.158.84
1,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,8.8.8.8
2,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,mail.google.com
3,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,142.250.29.139
4,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,dns.google
5,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,142.250.29.95
6,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,google.com
7,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,192.178.158.95
8,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,ssl.gstatic.com
9,EPIEJIZC,host-bbae,E6:AF:E8:AA:EA:49,unit-echo,web,2026-09-10 00:01:34,11-09-2026 09:46:01,142.250.182.227

In [18]:
display(security.head(10))

,endpoint_id,endpoint_name,mac,unit,log_type,event_time,received_time,message
0,EPZRAPEL,host-d14b,8A:58:3E:18:FD:1B,unit-foxtrot,quarantine,2026-09-01 04:58:58,01-09-2026 04:58:56,No suspicious file found by type or extension.
1,EPZRAPEL,host-d14b,8A:58:3E:18:FD:1B,unit-foxtrot,quarantine,2026-09-01 04:58:58,01-09-2026 04:58:56,File: 53EDA42869D426262B752F088EA605187284ACE8 | Quarantined At: 2026-08-31 13:21 | FileType: Ma...
2,EPYJFFRM,host-2864,F2:EA:9C:78:DC:3C,unit-oscar,quarantine,2026-09-01 05:20:37,01-09-2026 05:20:39,No suspicious file found by type or extension.
3,EPYJFFRM,host-2864,F2:EA:9C:78:DC:3C,unit-oscar,quarantine,2026-09-01 05:20:37,01-09-2026 05:20:39,No Malicious files found.
4,EPFFTO5T,host-508b,FA:2F:46:B7:14:23,unit-delta,quarantine,2026-09-01 08:50:38,01-09-2026 08:50:38,No suspicious file found by type or extension.
5,EPQA4SVZ,host-42d1,FE:6A:76:84:06:E3,unit-november,quarantine,2026-09-01 08:31:01,01-09-2026 08:31:01,No suspicious file found by type or extension.
6,EP5KBVLG,host-ee2b,66:E2:12:14:24:01,unit-romeo,quarantine,2026-09-01 08:26:20,01-09-2026 08:28:21,No Malicious files found.
7,EP5KBVLG,host-ee2b,66:E2:12:14:24:01,unit-romeo,quarantine,2026-09-01 08:26:20,01-09-2026 08:28:21,No suspicious file found by type or extension.
8,EP3XZALW,host-d144,22:27:EF:77:A1:EC,unit-charlie,quarantine,2026-09-01 08:29:39,01-09-2026 08:29:49,No suspicious file found by type or extension.
9,EPQA4SVZ,host-42d1,FE:6A:76:84:06:E3,unit-november,quarantine,2026-09-01 08:31:01,01-09-2026 08:31:01,No Malicious files found.

In [19]:
display(usb.head(10))

,endpoint_id,endpoint_name,mac,unit,log_type,event_time,received_time,message
0,EPD24DBC,host-7394,6E:DE:00:D5:9F:8A,unit-foxtrot,usb,2026-09-22 18:23:12,22-09-2026 19:03:03,"General -UDisk , Mass Storage abcd:1234"
1,EPD24DBC,host-7394,6E:DE:00:D5:9F:8A,unit-foxtrot,usb,2026-09-22 18:23:41,22-09-2026 19:03:03,"General -UDisk , Mass Storage abcd:1234"
2,EPD24DBC,host-7394,6E:DE:00:D5:9F:8A,unit-foxtrot,usb,2026-09-22 18:23:12,23-09-2026 09:05:16,"General -UDisk , Mass Storage abcd:1234"
3,EPD24DBC,host-7394,6E:DE:00:D5:9F:8A,unit-foxtrot,usb,2026-09-22 18:23:41,23-09-2026 09:05:16,"General -UDisk , Mass Storage abcd:1234"
4,EP7FZ2XY,host-9764,F6:6F:85:06:00:26,unit-quebec,usb,2026-09-07 22:34:11,07-09-2026 09:03:19,"usb-usage: Logitech-USB Optical Mouse, Human Interface Device 046d:c077"
5,EP7FZ2XY,host-9764,F6:6F:85:06:00:26,unit-quebec,usb,2026-09-07 22:34:12,07-09-2026 09:03:19,"usb-usage: Logitech-USB Optical Mouse, Human Interface Device 046d:c077"
6,EP7FZ2XY,host-9764,F6:6F:85:06:00:26,unit-quebec,usb,2026-09-07 22:34:13,07-09-2026 09:03:19,"usb-usage: Logitech-USB Optical Mouse, Human Interface Device 046d:c077"
7,EP7FZ2XY,host-9764,F6:6F:85:06:00:26,unit-quebec,usb,2026-09-07 22:34:14,07-09-2026 09:03:19,"usb-usage: Logitech-USB Optical Mouse, Human Interface Device 046d:c077"

In [9]:
print("WEB ACTIVITY TYPES")
print(web.dtypes)

print("\nENDPOINT SECURITY TYPES")
print(security.dtypes)

print("\nUSB TYPES")
print(usb.dtypes)

WEB ACTIVITY TYPES
endpoint_id      str
endpoint_name    str
mac              str
unit             str
log_type         str
event_time       str
received_time    str
message          str
dtype: object

ENDPOINT SECURITY TYPES
endpoint_id      str
endpoint_name    str
mac              str
unit             str
log_type         str
event_time       str
received_time    str
message          str
dtype: object

USB TYPES
endpoint_id      str
endpoint_name    str
mac              str
unit             str
log_type         str
event_time       str
received_time    str
message          str
dtype: object

In [10]:
print("Unique web endpoints:",
      web["endpoint_id"].nunique())

print("Unique security endpoints:",
      security["endpoint_id"].nunique())

print("Unique USB endpoints:",
      usb["endpoint_id"].nunique())

Unique web endpoints: 248
Unique security endpoints: 247
Unique USB endpoints: 2

In [11]:
print("Number of units:", web["unit"].nunique())

print("\nEndpoints by unit:")
display(
    web.groupby("unit")["endpoint_id"]
       .nunique()
       .sort_values(ascending=False)
)

Number of units: 19

Endpoints by unit:

unit
unit-charlie     20
unit-golf        20
unit-india       17
unit-quebec      17
unit-romeo       16
unit-echo        15
unit-lima        15
unit-bravo       14
unit-alpha       14
unit-foxtrot     14
unit-delta       14
unit-papa        12
unit-oscar       12
unit-kilo        11
unit-november    10
unit-juliett      9
unit-hotel        7
unit-sierra       7
unit-mike         4
Name: endpoint_id, dtype: int64

In [12]:
print("Web log types:")
display(web["log_type"].value_counts())

print("\nSecurity log types:")
display(security["log_type"].value_counts())

Web log types:

log_type
web    2812118
Name: count, dtype: int64

Security log types:

log_type
quarantine    20004
av_scan        2622
web_block       914
Name: count, dtype: int64

In [13]:
web["event_time"] = pd.to_datetime(
    web["event_time"],
    format="%d-%m-%Y %H:%M:%S",
    errors="coerce"
)

security["event_time"] = pd.to_datetime(
    security["event_time"],
    format="%d-%m-%Y %H:%M:%S",
    errors="coerce"
)

usb["event_time"] = pd.to_datetime(
    usb["event_time"],
    format="%d-%m-%Y %H:%M:%S",
    errors="coerce"
)

In [14]:
print("WEB ACTIVITY")
print("Start:", web["event_time"].min())
print("End:  ", web["event_time"].max())

print("\nENDPOINT SECURITY")
print("Start:", security["event_time"].min())
print("End:  ", security["event_time"].max())

print("\nUSB")
print("Start:", usb["event_time"].min())
print("End:  ", usb["event_time"].max())

WEB ACTIVITY
Start: 2026-09-10 00:01:34
End:   2026-09-21 23:09:01

ENDPOINT SECURITY
Start: 2026-09-01 01:15:01
End:   2026-09-26 22:10:02

USB
Start: 2026-09-07 22:34:11
End:   2026-09-22 18:23:41

In [15]:
print("WEB ACTIVITY — missing values")
display(web.isna().sum())

print("\nENDPOINT SECURITY — missing values")
display(security.isna().sum())

print("\nUSB — missing values")
display(usb.isna().sum())

WEB ACTIVITY — missing values

endpoint_id      0
endpoint_name    0
mac              0
unit             0
log_type         0
event_time       0
received_time    0
message          0
dtype: int64

ENDPOINT SECURITY — missing values

endpoint_id      0
endpoint_name    0
mac              0
unit             0
log_type         0
event_time       0
received_time    0
message          0
dtype: int64

USB — missing values

endpoint_id      0
endpoint_name    0
mac              0
unit             0
log_type         0
event_time       0
received_time    0
message          0
dtype: int64

In [16]:
web[web["endpoint_id"] == "EPSES7ZK"]

,endpoint_id,endpoint_name,mac,unit,log_type,event_time,received_time,message
86254,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-10 10:42:13,11-09-2026 08:44:35,n22ce.svc-72dec3.example
86255,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-10 10:42:13,11-09-2026 08:44:35,n9fa9.svc-347513.example
86256,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-10 10:42:13,11-09-2026 08:44:35,142.251.223.14
86257,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-10 10:42:13,11-09-2026 08:44:35,198.19.153.92
86258,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-10 10:42:13,11-09-2026 08:44:35,www.google.com
...,...,...,...,...,...,...,...,...
2762083,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-20 12:41:35,21-09-2026 08:29:33,13.35.20.9
2762084,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-20 12:41:35,21-09-2026 08:29:33,192.178.211.156
2762085,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-20 12:41:35,21-09-2026 08:29:33,px.ads.linkedin.com
2762086,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-20 12:41:35,21-09-2026 08:29:33,216.239.34.181
2762087,EPSES7ZK,host-4c8d,5A:26:AC:95:F8:C6,unit-papa,web,2026-09-20 12:41:35,21-09-2026 08:29:33,192.29.69.178

In [20]:
print("WEB ACTIVITY")
display(web["log_type"].value_counts())

print("\nENDPOINT SECURITY")
display(security["log_type"].value_counts())

print("\nUSB EVENTS")
display(usb["log_type"].value_counts())

WEB ACTIVITY

log_type
web    2812118
Name: count, dtype: int64

ENDPOINT SECURITY

log_type
quarantine    20004
av_scan        2622
web_block       914
Name: count, dtype: int64

USB EVENTS

log_type
usb    8
Name: count, dtype: int64

In [21]:
# Examine AV messages
av = security[security["log_type"] == "av_scan"]

print("Number of AV events:", len(av))

display(av[["endpoint_id", "event_time", "message"]].head(30))

Number of AV events: 2622

,endpoint_id,event_time,message
611,EPT4VYZW,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
612,EP2EVFKU,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
615,EPPXBL74,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
631,EPG67237,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
642,EPGHTVEF,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
678,EPEPTYRN,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
767,EP7FZ2XY,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
790,EPNWM26Q,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
791,EPLZ6PWJ,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
794,EPHBRTQ2,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
865,EPKTB5NE,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
902,EPDVCZ3P,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
914,EPFFTO5T,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
916,EPQIWPBQ,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
924,EPYJFFRM,2026-09-01 01:15:02,Infected file is ----- System Scan Completed ------
929,EPQHPXVS,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
934,EPNCY7H3,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
943,EPV7MB2K,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
949,EPO7DU5Z,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
959,EPMVZYZO,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
965,EPMDU6L5,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
966,EP6TZCQ6,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
967,EP6TZCQ6,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
976,EP4RS3P7,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
978,EPUTB7FS,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
1022,EPRD7FJT,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
1048,EPJRQKEK,2026-09-01 01:15:02,Infected file is ----- System Scan Completed ------
1049,EPX6YJD7,2026-09-01 01:15:01,Infected file is ----- System Scan Completed ------
1052,EPMQTKSL,2026-09-01 01:15:02,Infected file is ----- System Scan Completed ------
1053,EPMQTKSL,2026-09-01 01:15:02,Infected file is Infected files found. Beginning quarantine...

In [22]:
print(
    av["message"]
    .str.split(":", n=1)
    .str[0]
    .value_counts()
    .head(30)
)

message
Infected file is ----- System Scan Completed ------               2421
Infected file is Attempting to handle                               50
Infected file is Infected files found. Beginning quarantine...      43
Infected file is Processing                                         36
Infected file is Quarantined and deleted                            36
Knownviruses                                                        22
Infected file is File not found or no permissions                   14
Name: count, dtype: int64

In [23]:
quarantine = security[
    security["log_type"] == "quarantine"
]

print("Number of quarantine events:", len(quarantine))

display(
    quarantine[
        ["endpoint_id", "event_time", "message"]
    ].head(30)
)

Number of quarantine events: 20004

,endpoint_id,event_time,message
0,EPZRAPEL,2026-09-01 04:58:58,No suspicious file found by type or extension.
1,EPZRAPEL,2026-09-01 04:58:58,File: 53EDA42869D426262B752F088EA605187284ACE8 | Quarantined At: 2026-08-31 13:21 | FileType: Ma...
2,EPYJFFRM,2026-09-01 05:20:37,No suspicious file found by type or extension.
3,EPYJFFRM,2026-09-01 05:20:37,No Malicious files found.
4,EPFFTO5T,2026-09-01 08:50:38,No suspicious file found by type or extension.
5,EPQA4SVZ,2026-09-01 08:31:01,No suspicious file found by type or extension.
6,EP5KBVLG,2026-09-01 08:26:20,No Malicious files found.
7,EP5KBVLG,2026-09-01 08:26:20,No suspicious file found by type or extension.
8,EP3XZALW,2026-09-01 08:29:39,No suspicious file found by type or extension.
9,EPQA4SVZ,2026-09-01 08:31:01,No Malicious files found.
10,EPMY53PL,2026-09-01 08:35:07,No suspicious file found by type or extension.
11,EPMY53PL,2026-09-01 08:35:07,No Malicious files found.
12,EPGBKH56,2026-09-01 08:37:38,No suspicious file found by type or extension.
13,EP7XJK3C,2026-09-01 08:37:45,No Malicious files found.
14,EP7XJK3C,2026-09-01 08:37:45,No suspicious file found by type or extension.
15,EPGBKH56,2026-09-01 08:37:38,No Malicious files found.
16,EPFE66OS,2026-09-01 08:37:54,No Malicious files found.
17,EP3XZALW,2026-09-01 08:29:39,No Malicious files found.
18,EP7OWDTR,2026-09-01 08:26:07,No Malicious files found.
19,EP7OWDTR,2026-09-01 08:26:07,No suspicious file found by type or extension.
20,EPYJFFRM,2026-09-01 08:11:09,No Malicious files found.
21,EPAR5TSH,2026-09-01 08:15:24,No Malicious files found.
22,EPDO62BH,2026-09-01 08:20:33,No Malicious files found.
23,EPDO62BH,2026-09-01 08:20:33,No suspicious file found by type or extension.
24,EP5DHOIP,2026-09-01 08:22:00,No suspicious file found by type or extension.
25,EP5DHOIP,2026-09-01 08:22:00,No Malicious files found.
26,EPJ42VCZ,2026-09-01 08:23:08,No Malicious files found.
27,EPJ42VCZ,2026-09-01 08:23:08,No suspicious file found by type or extension.
28,EPFF7UHG,2026-09-01 08:20:33,No suspicious file found by type or extension.
29,EP2C4ZH5,2026-09-01 08:20:22,No suspicious file found by type or extension.

In [24]:
blocks = security[
    security["log_type"] == "web_block"
]

print("Number of web-block events:", len(blocks))

display(
    blocks[
        ["endpoint_id", "event_time", "message"]
    ].head(30)
)

Number of web-block events: 914

     endpoint_id          event_time           message
793     EPNWM26Q 2026-09-01 13:26:13          groww.in
796     EPNWM26Q 2026-09-01 13:27:13          groww.in
921     EPQHPXVS 2026-09-01 17:47:17  sync.aralego.com
1077    EPNXD2NI 2026-09-01 12:31:12     api.ipify.org
1078    EPNXD2NI 2026-09-01 12:36:12     api.ipify.org
1079    EPNXD2NI 2026-09-01 12:46:12     api.ipify.org
1081    EPNXD2NI 2026-09-01 12:33:12     api.ipify.org
1082    EPNXD2NI 2026-09-01 12:43:12     api.ipify.org
1083    EPNXD2NI 2026-09-01 12:49:12     api.ipify.org
1084    EPNXD2NI 2026-09-01 12:36:12     api.ipify.org
1085    EPNXD2NI 2026-09-01 12:46:12     api.ipify.org
1087    EPNXD2NI 2026-09-01 12:34:12     api.ipify.org
1088    EPNXD2NI 2026-09-01 12:44:12     api.ipify.org
1089    EPNXD2NI 2026-09-01 12:50:12     api.ipify.org
1091    EPNXD2NI 2026-09-01 12:34:12     api.ipify.org
1092    EPNXD2NI 2026-09-01 12:44:12     api.ipify.org
1093    EPNXD2NI 2026-09-01 12:50:12     api.ipify.org
1094    EPNXD2NI 2026-09-01 12:26:12     api.ipify.org
1115    EPIHPLA2 2026-09-01 12:18:12  www.facebook.com
1116    EPIHPLA2 2026-09-01 12:22:12  www.facebook.com
1117    EPIHPLA2 2026-09-01 17:56:17  www.facebook.com
1118    EPIHPLA2 2026-09-01 12:19:12  www.facebook.com
1169    EPNXD2NI 2026-09-01 12:52:12     api.ipify.org
1170    EPNXD2NI 2026-09-01 12:34:12     api.ipify.org
1171    EPNXD2NI 2026-09-01 12:45:12     api.ipify.org
1172    EPNXD2NI 2026-09-01 12:32:12     api.ipify.org
1173    EPNXD2NI 2026-09-01 12:43:12     api.ipify.org
1174    EPNXD2NI 2026-09-01 12:49:12     api.ipify.org
1175    EPNXD2NI 2026-09-01 12:34:12     api.ipify.org
1176    EPNXD2NI 2026-09-01 12:45:12     api.ipify.org

In [25]:
print("Endpoints with AV events:",
      av["endpoint_id"].nunique())

print("Endpoints with quarantine events:",
      quarantine["endpoint_id"].nunique())

print("Endpoints with web blocks:",
      blocks["endpoint_id"].nunique())

print("Endpoints with any security event:",
      security["endpoint_id"].nunique())

Endpoints with AV events: 214
Endpoints with quarantine events: 244
Endpoints with web blocks: 74
Endpoints with any security event: 247

In [26]:
# Very important: understand quarantine duplication

q = quarantine.copy()

print(
    "Raw quarantine rows:",
    len(q)
)

Raw quarantine rows: 20004

In [27]:
print(
    "Unique endpoint + message:",
    q.drop_duplicates(
        subset=["endpoint_id", "message"]
    ).shape[0]
)

Unique endpoint + message: 591

In [28]:
# Extract AV records that indicate an actual infected file detection
av_detections = av[
    av["message"].str.contains(
        r"Infected file is .*FOUND",
        case=False,
        na=False,
        regex=True
    )
].copy()

print("Actual AV detection records:", len(av_detections))

display(
    av_detections[
        ["endpoint_id", "event_time", "message"]
    ].sort_values("event_time").head(50)
)

Actual AV detection records: 57

,endpoint_id,event_time,message
1156,EPC2L3UH,2026-09-01 01:15:01,Infected file is Infected files found. Beginning quarantine...
3524,EPLFOXSS,2026-09-01 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
3527,EPLFOXSS,2026-09-01 01:15:01,Infected file is Infected files found. Beginning quarantine...
1053,EPMQTKSL,2026-09-01 01:15:02,Infected file is Infected files found. Beginning quarantine...
3525,EPLFOXSS,2026-09-02 01:15:01,Infected file is Infected files found. Beginning quarantine...
3531,EPLFOXSS,2026-09-02 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
3802,EPC2L3UH,2026-09-03 01:15:01,Infected file is Infected files found. Beginning quarantine...
5178,EPLFOXSS,2026-09-05 01:15:01,Infected file is Infected files found. Beginning quarantine...
5181,EPLFOXSS,2026-09-05 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
11679,EPJYEC7F,2026-09-05 01:15:01,Infected file is Infected files found. Beginning quarantine...
6212,EPC2L3UH,2026-09-07 01:15:01,Infected file is Infected files found. Beginning quarantine...
12090,EPLFOXSS,2026-09-07 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12088,EPLFOXSS,2026-09-07 01:15:01,Infected file is Infected files found. Beginning quarantine...
13827,EPQKOBYG,2026-09-07 01:15:01,Infected file is Infected files found. Beginning quarantine...
12094,EPLFOXSS,2026-09-08 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
6829,EPC2L3UH,2026-09-08 01:15:01,Infected file is Infected files found. Beginning quarantine...
12092,EPLFOXSS,2026-09-08 01:15:01,Infected file is Infected files found. Beginning quarantine...
12096,EPLFOXSS,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
8488,EPR4BEDS,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
8300,EPC2L3UH,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
7962,EPFQSCDV,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
12098,EPLFOXSS,2026-09-09 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
9254,EPGSQVEB,2026-09-10 01:15:01,Infected file is Infected files found. Beginning quarantine...
12100,EPLFOXSS,2026-09-10 01:15:02,Infected file is Infected files found. Beginning quarantine...
12102,EPLFOXSS,2026-09-10 01:15:02,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
9922,EPC2L3UH,2026-09-11 01:15:01,Infected file is Infected files found. Beginning quarantine...
10340,EPDRB236,2026-09-12 01:15:01,Infected file is Infected files found. Beginning quarantine...
12104,EPLFOXSS,2026-09-12 01:15:01,Infected file is Infected files found. Beginning quarantine...
11995,EPLFOXSS,2026-09-12 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
13744,EPC2L3UH,2026-09-14 01:15:01,Infected file is Infected files found. Beginning quarantine...
12239,EPLFOXSS,2026-09-14 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12243,EPLFOXSS,2026-09-14 01:15:01,Infected file is Infected files found. Beginning quarantine...
13666,EPLFOXSS,2026-09-15 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
13701,EPJYEC7F,2026-09-15 01:15:01,Infected file is Infected files found. Beginning quarantine...
13742,EPC2L3UH,2026-09-15 01:15:01,Infected file is Infected files found. Beginning quarantine...
13664,EPLFOXSS,2026-09-15 01:15:01,Infected file is Infected files found. Beginning quarantine...
14503,EPJYEC7F,2026-09-16 01:15:01,Infected file is Infected files found. Beginning quarantine...
14506,EPLFOXSS,2026-09-16 01:15:01,Infected file is Infected files found. Beginning quarantine...
14508,EPLFOXSS,2026-09-16 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
14609,EPC2L3UH,2026-09-16 01:15:01,Infected file is Infected files found. Beginning quarantine...
18923,EPJYEC7F,2026-09-17 01:15:01,Infected file is Infected files found. Beginning quarantine...
18160,EPLFOXSS,2026-09-17 01:15:01,Infected file is Infected files found. Beginning quarantine...
18156,EPLFOXSS,2026-09-17 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
15358,EPC2L3UH,2026-09-17 01:15:01,Infected file is Infected files found. Beginning quarantine...
18157,EPLFOXSS,2026-09-18 01:15:01,Infected file is Infected files found. Beginning quarantine...
18935,EPJYEC7F,2026-09-18 01:15:01,Infected file is Infected files found. Beginning quarantine...
18155,EPLFOXSS,2026-09-18 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
17964,EP3GALVS,2026-09-19 01:15:01,Infected file is Infected files found. Beginning quarantine...
18158,EPLFOXSS,2026-09-19 01:15:01,Infected file is Infected files found. Beginning quarantine...
18167,EPLFOXSS,2026-09-19 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...

In [29]:
print("Endpoints with actual AV detections:",
      av_detections["endpoint_id"].nunique())

display(
    av_detections["endpoint_id"]
    .value_counts()
    .head(30)
)

Endpoints with actual AV detections: 13

endpoint_id
EPLFOXSS    28
EPC2L3UH    12
EPJYEC7F     6
EPAX5P5D     2
EPMQTKSL     1
EPFQSCDV     1
EPR4BEDS     1
EPGSQVEB     1
EPDRB236     1
EPQKOBYG     1
EP3GALVS     1
EPSES7ZK     1
EPVSWBNA     1
Name: count, dtype: int64

In [30]:
display(
    av_detections[
        ["endpoint_id", "event_time", "message"]
    ]
    .sort_values(["endpoint_id", "event_time"])
)

,endpoint_id,event_time,message
17964,EP3GALVS,2026-09-19 01:15:01,Infected file is Infected files found. Beginning quarantine...
21800,EPAX5P5D,2026-09-22 01:15:01,Infected file is Infected files found. Beginning quarantine...
21810,EPAX5P5D,2026-09-23 01:15:01,Infected file is Infected files found. Beginning quarantine...
1156,EPC2L3UH,2026-09-01 01:15:01,Infected file is Infected files found. Beginning quarantine...
3802,EPC2L3UH,2026-09-03 01:15:01,Infected file is Infected files found. Beginning quarantine...
6212,EPC2L3UH,2026-09-07 01:15:01,Infected file is Infected files found. Beginning quarantine...
6829,EPC2L3UH,2026-09-08 01:15:01,Infected file is Infected files found. Beginning quarantine...
8300,EPC2L3UH,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
9922,EPC2L3UH,2026-09-11 01:15:01,Infected file is Infected files found. Beginning quarantine...
13744,EPC2L3UH,2026-09-14 01:15:01,Infected file is Infected files found. Beginning quarantine...
13742,EPC2L3UH,2026-09-15 01:15:01,Infected file is Infected files found. Beginning quarantine...
14609,EPC2L3UH,2026-09-16 01:15:01,Infected file is Infected files found. Beginning quarantine...
15358,EPC2L3UH,2026-09-17 01:15:01,Infected file is Infected files found. Beginning quarantine...
19450,EPC2L3UH,2026-09-21 01:15:01,Infected file is Infected files found. Beginning quarantine...
20118,EPC2L3UH,2026-09-22 01:15:01,Infected file is Infected files found. Beginning quarantine...
10340,EPDRB236,2026-09-12 01:15:01,Infected file is Infected files found. Beginning quarantine...
7962,EPFQSCDV,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
9254,EPGSQVEB,2026-09-10 01:15:01,Infected file is Infected files found. Beginning quarantine...
11679,EPJYEC7F,2026-09-05 01:15:01,Infected file is Infected files found. Beginning quarantine...
13701,EPJYEC7F,2026-09-15 01:15:01,Infected file is Infected files found. Beginning quarantine...
14503,EPJYEC7F,2026-09-16 01:15:01,Infected file is Infected files found. Beginning quarantine...
18923,EPJYEC7F,2026-09-17 01:15:01,Infected file is Infected files found. Beginning quarantine...
18935,EPJYEC7F,2026-09-18 01:15:01,Infected file is Infected files found. Beginning quarantine...
18922,EPJYEC7F,2026-09-19 01:15:01,Infected file is Infected files found. Beginning quarantine...
3524,EPLFOXSS,2026-09-01 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
3527,EPLFOXSS,2026-09-01 01:15:01,Infected file is Infected files found. Beginning quarantine...
3525,EPLFOXSS,2026-09-02 01:15:01,Infected file is Infected files found. Beginning quarantine...
3531,EPLFOXSS,2026-09-02 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
5178,EPLFOXSS,2026-09-05 01:15:01,Infected file is Infected files found. Beginning quarantine...
5181,EPLFOXSS,2026-09-05 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12088,EPLFOXSS,2026-09-07 01:15:01,Infected file is Infected files found. Beginning quarantine...
12090,EPLFOXSS,2026-09-07 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12092,EPLFOXSS,2026-09-08 01:15:01,Infected file is Infected files found. Beginning quarantine...
12094,EPLFOXSS,2026-09-08 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12096,EPLFOXSS,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
12098,EPLFOXSS,2026-09-09 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12100,EPLFOXSS,2026-09-10 01:15:02,Infected file is Infected files found. Beginning quarantine...
12102,EPLFOXSS,2026-09-10 01:15:02,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
11995,EPLFOXSS,2026-09-12 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12104,EPLFOXSS,2026-09-12 01:15:01,Infected file is Infected files found. Beginning quarantine...
12239,EPLFOXSS,2026-09-14 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12243,EPLFOXSS,2026-09-14 01:15:01,Infected file is Infected files found. Beginning quarantine...
13664,EPLFOXSS,2026-09-15 01:15:01,Infected file is Infected files found. Beginning quarantine...
13666,EPLFOXSS,2026-09-15 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
14506,EPLFOXSS,2026-09-16 01:15:01,Infected file is Infected files found. Beginning quarantine...
14508,EPLFOXSS,2026-09-16 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
18156,EPLFOXSS,2026-09-17 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
18160,EPLFOXSS,2026-09-17 01:15:01,Infected file is Infected files found. Beginning quarantine...
18155,EPLFOXSS,2026-09-18 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
18157,EPLFOXSS,2026-09-18 01:15:01,Infected file is Infected files found. Beginning quarantine...
18158,EPLFOXSS,2026-09-19 01:15:01,Infected file is Infected files found. Beginning quarantine...
18167,EPLFOXSS,2026-09-19 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
1053,EPMQTKSL,2026-09-01 01:15:02,Infected file is Infected files found. Beginning quarantine...
13827,EPQKOBYG,2026-09-07 01:15:01,Infected file is Infected files found. Beginning quarantine...
8488,EPR4BEDS,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
18771,EPSES7ZK,2026-09-21 01:15:01,Infected file is Infected files found. Beginning quarantine...
21722,EPVSWBNA,2026-09-23 01:15:01,Infected file is Infected files found. Beginning quarantine...

In [31]:
top_av_endpoints = [
    "EPLFOXSS",
    "EPC2L3UH",
    "EPJYEC7F"
]

display(
    av_detections[
        av_detections["endpoint_id"].isin(top_av_endpoints)
    ][
        ["endpoint_id", "event_time", "message"]
    ]
    .sort_values(["endpoint_id", "event_time"])
)

,endpoint_id,event_time,message
1156,EPC2L3UH,2026-09-01 01:15:01,Infected file is Infected files found. Beginning quarantine...
3802,EPC2L3UH,2026-09-03 01:15:01,Infected file is Infected files found. Beginning quarantine...
6212,EPC2L3UH,2026-09-07 01:15:01,Infected file is Infected files found. Beginning quarantine...
6829,EPC2L3UH,2026-09-08 01:15:01,Infected file is Infected files found. Beginning quarantine...
8300,EPC2L3UH,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
9922,EPC2L3UH,2026-09-11 01:15:01,Infected file is Infected files found. Beginning quarantine...
13744,EPC2L3UH,2026-09-14 01:15:01,Infected file is Infected files found. Beginning quarantine...
13742,EPC2L3UH,2026-09-15 01:15:01,Infected file is Infected files found. Beginning quarantine...
14609,EPC2L3UH,2026-09-16 01:15:01,Infected file is Infected files found. Beginning quarantine...
15358,EPC2L3UH,2026-09-17 01:15:01,Infected file is Infected files found. Beginning quarantine...
19450,EPC2L3UH,2026-09-21 01:15:01,Infected file is Infected files found. Beginning quarantine...
20118,EPC2L3UH,2026-09-22 01:15:01,Infected file is Infected files found. Beginning quarantine...
11679,EPJYEC7F,2026-09-05 01:15:01,Infected file is Infected files found. Beginning quarantine...
13701,EPJYEC7F,2026-09-15 01:15:01,Infected file is Infected files found. Beginning quarantine...
14503,EPJYEC7F,2026-09-16 01:15:01,Infected file is Infected files found. Beginning quarantine...
18923,EPJYEC7F,2026-09-17 01:15:01,Infected file is Infected files found. Beginning quarantine...
18935,EPJYEC7F,2026-09-18 01:15:01,Infected file is Infected files found. Beginning quarantine...
18922,EPJYEC7F,2026-09-19 01:15:01,Infected file is Infected files found. Beginning quarantine...
3524,EPLFOXSS,2026-09-01 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
3527,EPLFOXSS,2026-09-01 01:15:01,Infected file is Infected files found. Beginning quarantine...
3525,EPLFOXSS,2026-09-02 01:15:01,Infected file is Infected files found. Beginning quarantine...
3531,EPLFOXSS,2026-09-02 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
5178,EPLFOXSS,2026-09-05 01:15:01,Infected file is Infected files found. Beginning quarantine...
5181,EPLFOXSS,2026-09-05 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12088,EPLFOXSS,2026-09-07 01:15:01,Infected file is Infected files found. Beginning quarantine...
12090,EPLFOXSS,2026-09-07 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12092,EPLFOXSS,2026-09-08 01:15:01,Infected file is Infected files found. Beginning quarantine...
12094,EPLFOXSS,2026-09-08 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12096,EPLFOXSS,2026-09-09 01:15:01,Infected file is Infected files found. Beginning quarantine...
12098,EPLFOXSS,2026-09-09 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12100,EPLFOXSS,2026-09-10 01:15:02,Infected file is Infected files found. Beginning quarantine...
12102,EPLFOXSS,2026-09-10 01:15:02,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
11995,EPLFOXSS,2026-09-12 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12104,EPLFOXSS,2026-09-12 01:15:01,Infected file is Infected files found. Beginning quarantine...
12239,EPLFOXSS,2026-09-14 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
12243,EPLFOXSS,2026-09-14 01:15:01,Infected file is Infected files found. Beginning quarantine...
13664,EPLFOXSS,2026-09-15 01:15:01,Infected file is Infected files found. Beginning quarantine...
13666,EPLFOXSS,2026-09-15 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
14506,EPLFOXSS,2026-09-16 01:15:01,Infected file is Infected files found. Beginning quarantine...
14508,EPLFOXSS,2026-09-16 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
18156,EPLFOXSS,2026-09-17 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
18160,EPLFOXSS,2026-09-17 01:15:01,Infected file is Infected files found. Beginning quarantine...
18155,EPLFOXSS,2026-09-18 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...
18157,EPLFOXSS,2026-09-18 01:15:01,Infected file is Infected files found. Beginning quarantine...
18158,EPLFOXSS,2026-09-19 01:15:01,Infected file is Infected files found. Beginning quarantine...
18167,EPLFOXSS,2026-09-19 01:15:01,Infected file is File not found or no permissions: '/home/user6405/.local/share/evolution/mail/l...

In [32]:
known_candidates = [
    "EPMQTKSL",
    "EPSES7ZK",
    "EPVSWBNA"
]

display(
    av_detections[
        av_detections["endpoint_id"].isin(known_candidates)
    ][
        ["endpoint_id", "event_time", "message"]
    ]
    .sort_values(["endpoint_id", "event_time"])
)

,endpoint_id,event_time,message
1053,EPMQTKSL,2026-09-01 01:15:02,Infected file is Infected files found. Beginning quarantine...
18771,EPSES7ZK,2026-09-21 01:15:01,Infected file is Infected files found. Beginning quarantine...
21722,EPVSWBNA,2026-09-23 01:15:01,Infected file is Infected files found. Beginning quarantine...

In [33]:
# Now connect AV detection → quarantine

malicious_quarantine = quarantine[
    quarantine["message"].str.contains(
        "FileType:\s*Malicious",
        case=False,
        na=False,
        regex=True
    )
].copy()

print(
    "Quarantine records marked malicious:",
    len(malicious_quarantine)
)

print(
    "Endpoints with malicious quarantine records:",
    malicious_quarantine["endpoint_id"].nunique()
)

display(
    malicious_quarantine[
        ["endpoint_id", "event_time", "message"]
    ].head(30)
)

Quarantine records marked malicious: 134
Endpoints with malicious quarantine records: 33

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Asus\AppData\Local\Temp\ipykernel_8028\4003893462.py:5: SyntaxWarning: invalid escape sequence '\s'
  "FileType:\s*Malicious",

,endpoint_id,event_time,message
1,EPZRAPEL,2026-09-01 04:58:58,File: 53EDA42869D426262B752F088EA605187284ACE8 | Quarantined At: 2026-08-31 13:21 | FileType: Ma...
394,EPOC6Y4R,2026-09-01 08:59:34,File: recently-used.xbel | Quarantined At: 2026-08-31 13:35 | FileType: Malicious | SHA256: 5e10...
671,EPOC6Y4R,2026-09-01 18:21:26,File: recently-used.xbel | Quarantined At: 2026-09-01 13:33 | FileType: Malicious | SHA256: 5e10...
995,EPJYEC7F,2026-09-01 08:09:22,File: recently-used.xbel | Quarantined At: 2026-08-31 13:17 | FileType: Malicious | SHA256: 5e10...
1045,EPMQTKSL,2026-09-02 08:37:11,File: recently-used.xbel | Quarantined At: 2026-09-01 13:56 | FileType: Malicious | SHA256: 5e10...
1050,EPOC6Y4R,2026-09-02 08:39:53,File: recently-used.xbel | Quarantined At: 2026-09-01 13:33 | FileType: Malicious | SHA256: 5e10...
1148,EPC2L3UH,2026-09-02 08:48:22,File: recently-used.xbel | Quarantined At: 2026-09-01 13:17 | FileType: Malicious | SHA256: 5e10...
2843,EPOC6Y4R,2026-09-04 08:23:22,File: recently-used.xbel | Quarantined At: 2026-09-03 13:32 | FileType: Malicious | SHA256: 5e10...
2997,EPAGTKNF,2026-09-04 18:10:01,"File: Buy CP PLUS Dashboard Camera, Warranty NONE 1 year online _ Public Procurement Portal (PPP..."
3415,EPAGTKNF,2026-09-03 19:03:33,"File: Buy CP PLUS Dashboard Camera, Warranty NONE 1 year online _ Public Procurement Portal (PPP..."
3471,EPOC6Y4R,2026-09-03 19:14:05,File: recently-used.xbel | Quarantined At: 2026-09-03 13:32 | FileType: Malicious | SHA256: 5e10...
3801,EPC2L3UH,2026-09-05 08:58:56,File: recently-used.xbel | Quarantined At: 2026-09-03 13:17 | FileType: Malicious | SHA256: 5e10...
4998,EPJ42VCZ,2026-09-07 08:43:44,File: RAGHAV STNC STNA.pdf | Quarantined At: 2026-09-06 10:20 | FileType: Malicious | SHA256: a2...
4999,EPJ42VCZ,2026-09-07 08:43:44,File: RAGHAV STNA STNB.pdf | Quarantined At: 2026-09-06 10:32 | FileType: Malicious | SHA256: 85...
5596,EPPGWIOF,2026-09-07 13:58:49,File: brprintconflsr3 | Quarantined At: 2026-09-07 10:57 | FileType: Malicious | SHA256: 6594cac...
5607,EPPGWIOF,2026-09-07 13:58:49,File: rawtobr3 | Quarantined At: 2026-09-07 10:58 | FileType: Malicious | SHA256: 64efda7704564d...
5691,EPJYEC7F,2026-09-07 09:03:50,File: recently-used.xbel | Quarantined At: 2026-09-05 13:18 | FileType: Malicious | SHA256: 5e10...
5885,EPPGWIOF,2026-09-08 08:12:56,File: brprintconflsr3 | Quarantined At: 2026-09-07 10:57 | FileType: Malicious | SHA256: 6594cac...
5960,EPPGWIOF,2026-09-07 12:10:49,File: brprintconflsr3 | Quarantined At: 2026-09-07 10:57 | FileType: Malicious | SHA256: 6594cac...
5962,EPPGWIOF,2026-09-07 12:10:49,File: rawtobr3 | Quarantined At: 2026-09-07 10:58 | FileType: Malicious | SHA256: 64efda7704564d...
6104,EPPGWIOF,2026-09-07 11:47:20,File: rawtobr3 | Quarantined At: 2026-09-07 10:58 | FileType: Malicious | SHA256: 64efda7704564d...
6110,EPPGWIOF,2026-09-07 11:47:20,File: brprintconflsr3 | Quarantined At: 2026-09-07 10:57 | FileType: Malicious | SHA256: 6594cac...
6145,EPPGWIOF,2026-09-07 11:25:38,File: brprintconflsr3 | Quarantined At: 2026-09-07 10:57 | FileType: Malicious | SHA256: 6594cac...
6146,EPPGWIOF,2026-09-07 11:25:38,File: rawtobr3 | Quarantined At: 2026-09-07 10:58 | FileType: Malicious | SHA256: 64efda7704564d...
6190,EPQKOBYG,2026-09-08 08:31:09,File: win-lbp623-621-fw-v1301(1).exe | Quarantined At: 2026-09-07 13:57 | FileType: Malicious | ...
6215,EPC2L3UH,2026-09-08 08:41:56,File: recently-used.xbel | Quarantined At: 2026-09-07 13:17 | FileType: Malicious | SHA256: 5e10...
6369,EPPGWIOF,2026-09-08 08:12:56,File: rawtobr3 | Quarantined At: 2026-09-07 10:58 | FileType: Malicious | SHA256: 64efda7704564d...
6914,EPC2L3UH,2026-09-09 08:40:46,File: recently-used.xbel | Quarantined At: 2026-09-08 13:17 | FileType: Malicious | SHA256: 5e10...
7092,EPMDU6L5,2026-09-08 11:58:09,File: recently-used.xbel | Quarantined At: 2026-05-13 13:24 | FileType: Malicious | SHA256: 5dd5...
7603,EPFQSCDV,2026-09-09 18:05:21,File: recently-used.xbel | Quarantined At: 2026-09-09 13:18 | FileType: Malicious | SHA256: 5e10...

In [34]:
malicious_quarantine = quarantine[
    quarantine["message"].str.contains(
        "FileType: Malicious",
        case=False,
        na=False
    )
].copy()

In [35]:
# Start with quarantine records explicitly labelled as malicious
malicious_quarantine = quarantine[
    quarantine["message"].str.contains(
        "FileType: Malicious",
        case=False,
        na=False
    )
].copy()

print("Raw malicious quarantine records:",
      len(malicious_quarantine))

print("Endpoints:",
      malicious_quarantine["endpoint_id"].nunique())

Raw malicious quarantine records: 134
Endpoints: 33

In [36]:
# Remove known false-positive artifacts
malicious_clean = malicious_quarantine[
    ~malicious_quarantine["message"].str.contains(
        r"File:\s*recently-used\.xbel\b",
        case=False,
        na=False,
        regex=True
    )
].copy()

malicious_clean = malicious_clean[
    ~malicious_clean["message"].str.contains(
        r"File:\s*[^|]*\.desktop\b",
        case=False,
        na=False,
        regex=True
    )
].copy()

print("After false-positive filtering:",
      len(malicious_clean))

print("Endpoints:",
      malicious_clean["endpoint_id"].nunique())

After false-positive filtering: 85
Endpoints: 20

In [37]:
display(
    malicious_clean[
        ["endpoint_id", "event_time", "message"]
    ]
    .sort_values(["endpoint_id", "event_time"])
    .head(50)
)

,endpoint_id,event_time,message
9302,EP4YIFHV,2026-09-11 09:23:33,File: wallet_donation_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA25...
9352,EP4YIFHV,2026-09-11 09:23:33,File: load-ec-deps.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: ...
9524,EP4YIFHV,2026-09-11 09:23:33,File: runtime.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 569e4...
9535,EP4YIFHV,2026-09-11 09:23:33,File: tokenized-card.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256...
9536,EP4YIFHV,2026-09-11 09:23:33,File: bnpl_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 6c21396c...
9537,EP4YIFHV,2026-09-11 09:23:33,File: load-hub-i18n.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256:...
9538,EP4YIFHV,2026-09-11 09:23:33,File: c3f9c4a416e9e493005fc3f97adacbcf12956a81cc6c645d255fd023442c8120 | Quarantined At: 2026-09...
9539,EP4YIFHV,2026-09-11 09:23:33,File: load-ec-i18n.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: ...
9540,EP4YIFHV,2026-09-11 09:23:33,File: crypto.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 8e661d...
9553,EP4YIFHV,2026-09-11 09:23:33,File: notification_fast.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA...
9557,EP4YIFHV,2026-09-11 09:23:33,File: webui-setup.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: e3d95016...
9558,EP4YIFHV,2026-09-11 09:23:33,File: shopping_iframe_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA25...
9559,EP4YIFHV,2026-09-11 09:23:33,File: buynow_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: bee346...
9560,EP4YIFHV,2026-09-11 09:23:33,File: edge_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 985d0862...
9561,EP4YIFHV,2026-09-11 09:23:33,File: wallet-buynow.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256:...
9565,EP4YIFHV,2026-09-11 09:23:33,File: app-setup.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: d604ac767e...
9566,EP4YIFHV,2026-09-11 09:23:33,File: bnpl.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 620389d2...
9567,EP4YIFHV,2026-09-11 09:23:33,File: notification.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: ...
9568,EP4YIFHV,2026-09-11 09:23:33,File: miniwallet.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 6f...
9569,EP4YIFHV,2026-09-11 09:23:33,File: wallet_checkout_autofill_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Maliciou...
9274,EP4YIFHV,2026-09-11 09:35:09,File: bnpl.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 620389d2...
9275,EP4YIFHV,2026-09-11 09:35:09,File: bnpl_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 6c21396c...
9282,EP4YIFHV,2026-09-11 09:35:09,File: shopping_iframe_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA25...
9283,EP4YIFHV,2026-09-11 09:35:09,File: notification_fast.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA...
9284,EP4YIFHV,2026-09-11 09:35:09,File: load-hub-i18n.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256:...
9285,EP4YIFHV,2026-09-11 09:35:09,File: wallet_donation_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA25...
9286,EP4YIFHV,2026-09-11 09:35:09,File: edge_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 985d0862...
9315,EP4YIFHV,2026-09-11 09:35:09,File: c3f9c4a416e9e493005fc3f97adacbcf12956a81cc6c645d255fd023442c8120 | Quarantined At: 2026-09...
9316,EP4YIFHV,2026-09-11 09:35:09,File: webui-setup.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: e3d95016...
9317,EP4YIFHV,2026-09-11 09:35:09,File: wallet-buynow.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256:...
9318,EP4YIFHV,2026-09-11 09:35:09,File: notification.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: ...
9319,EP4YIFHV,2026-09-11 09:35:09,File: wallet_checkout_autofill_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Maliciou...
9320,EP4YIFHV,2026-09-11 09:35:09,File: crypto.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 8e661d...
9321,EP4YIFHV,2026-09-11 09:35:09,File: runtime.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 569e4...
9322,EP4YIFHV,2026-09-11 09:35:09,File: tokenized-card.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256...
9323,EP4YIFHV,2026-09-11 09:35:09,File: buynow_driver.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: bee346...
9324,EP4YIFHV,2026-09-11 09:35:09,File: load-ec-deps.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: ...
9325,EP4YIFHV,2026-09-11 09:35:09,File: load-ec-i18n.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: ...
9326,EP4YIFHV,2026-09-11 09:35:09,File: app-setup.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: d604ac767e...
9327,EP4YIFHV,2026-09-11 09:35:09,File: miniwallet.bundle.js | Quarantined At: 2026-09-10 13:30 | FileType: Malicious | SHA256: 6f...
23430,EP7UYCXM,2026-09-26 15:25:25,File: libeToken.so.10.7.77 | Quarantined At: 2026-09-26 08:17 | FileType: Malicious | SHA256: 57...
3415,EPAGTKNF,2026-09-03 19:03:33,"File: Buy CP PLUS Dashboard Camera, Warranty NONE 1 year online _ Public Procurement Portal (PPP..."
2997,EPAGTKNF,2026-09-04 18:10:01,"File: Buy CP PLUS Dashboard Camera, Warranty NONE 1 year online _ Public Procurement Portal (PPP..."
15257,EPAJI3E5,2026-09-17 16:43:44,File: Lakeside traders.docx | Quarantined At: 2026-09-17 12:44 | FileType: Malicious | SHA256: c...
15258,EPAJI3E5,2026-09-17 16:43:44,File: Lakeside traders.pdf | Quarantined At: 2026-09-17 12:59 | FileType: Malicious | SHA256: da...
15311,EPAJI3E5,2026-09-18 08:28:01,File: Lakeside traders.docx | Quarantined At: 2026-09-17 12:44 | FileType: Malicious | SHA256: c...
15312,EPAJI3E5,2026-09-18 08:28:01,File: Lakeside traders.pdf | Quarantined At: 2026-09-17 12:59 | FileType: Malicious | SHA256: da...
8169,EPEEHWSG,2026-09-10 09:15:06,File: Library Books.xlsx | Quarantined At: 2026-09-08 21:19 | FileType: Malicious | SHA256: 98d1...
9245,EPGSQVEB,2026-09-11 10:11:45,File: Final_Documents.zip | Quarantined At: 2026-09-10 15:38 | FileType: Malicious | SHA256: 404...
4998,EPJ42VCZ,2026-09-07 08:43:44,File: RAGHAV STNC STNA.pdf | Quarantined At: 2026-09-06 10:20 | FileType: Malicious | SHA256: a2...

In [38]:
malicious_clean["file_name"] = (
    malicious_clean["message"]
    .str.extract(r"File:\s*(.*?)\s*\|", expand=False)
)

display(
    malicious_clean[
        ["endpoint_id", "file_name"]
    ].head(30)
)

,endpoint_id,file_name
1,EPZRAPEL,53EDA42869D426262B752F088EA605187284ACE8
2997,EPAGTKNF,"Buy CP PLUS Dashboard Camera, Warranty NONE 1 year online _ Public Procurement Portal (PPP).pdf"
3415,EPAGTKNF,"Buy CP PLUS Dashboard Camera, Warranty NONE 1 year online _ Public Procurement Portal (PPP).pdf"
4998,EPJ42VCZ,RAGHAV STNC STNA.pdf
4999,EPJ42VCZ,RAGHAV STNA STNB.pdf
5596,EPPGWIOF,brprintconflsr3
5607,EPPGWIOF,rawtobr3
5885,EPPGWIOF,brprintconflsr3
5960,EPPGWIOF,brprintconflsr3
5962,EPPGWIOF,rawtobr3
6104,EPPGWIOF,rawtobr3
6110,EPPGWIOF,brprintconflsr3
6145,EPPGWIOF,brprintconflsr3
6146,EPPGWIOF,rawtobr3
6190,EPQKOBYG,win-lbp623-621-fw-v1301(1).exe
6369,EPPGWIOF,rawtobr3
8169,EPEEHWSG,Library Books.xlsx
9245,EPGSQVEB,Final_Documents.zip
9274,EP4YIFHV,bnpl.bundle.js
9275,EP4YIFHV,bnpl_driver.js
9282,EP4YIFHV,shopping_iframe_driver.js
9283,EP4YIFHV,notification_fast.bundle.js
9284,EP4YIFHV,load-hub-i18n.bundle.js
9285,EP4YIFHV,wallet_donation_driver.js
9286,EP4YIFHV,edge_driver.js
9302,EP4YIFHV,wallet_donation_driver.js
9315,EP4YIFHV,c3f9c4a416e9e493005fc3f97adacbcf12956a81cc6c645d255fd023442c8120
9316,EP4YIFHV,webui-setup.js
9317,EP4YIFHV,wallet-buynow.bundle.js
9318,EP4YIFHV,notification.bundle.js

In [39]:
malicious_clean["sha256"] = (
    malicious_clean["message"]
    .str.extract(
        r"SHA256:\s*([A-Fa-f0-9]{64})",
        expand=False
    )
)

display(
    malicious_clean[
        ["endpoint_id", "file_name", "sha256"]
    ].head(30)
)

,endpoint_id,file_name,sha256
1,EPZRAPEL,53EDA42869D426262B752F088EA605187284ACE8,2e4dff1672bbabba74a0a99d54e38e56e036ce8471989583039b3c3e7edac0b7
2997,EPAGTKNF,"Buy CP PLUS Dashboard Camera, Warranty NONE 1 year online _ Public Procurement Portal (PPP).pdf",18866b6f7308f73bc1b63193e50629bfd4fff701d6b9d3d2d6331b90e9162208
3415,EPAGTKNF,"Buy CP PLUS Dashboard Camera, Warranty NONE 1 year online _ Public Procurement Portal (PPP).pdf",18866b6f7308f73bc1b63193e50629bfd4fff701d6b9d3d2d6331b90e9162208
4998,EPJ42VCZ,RAGHAV STNC STNA.pdf,a2beca1870ae689f4b046a20c3d8e2e48557d782dea53489b21a8b0adcef38be
4999,EPJ42VCZ,RAGHAV STNA STNB.pdf,854b8f7716627df333e8ecfeae5887c02b3195658f7394573fe21b67e93e11be
5596,EPPGWIOF,brprintconflsr3,6594cac08d03782ad43d6b293faff904f20032c8eb37a1b27b6caf57b1aeae5e
5607,EPPGWIOF,rawtobr3,64efda7704564dd50c7514e74ef3c5252bc68af8f3b0d92358b64771980665af
5885,EPPGWIOF,brprintconflsr3,6594cac08d03782ad43d6b293faff904f20032c8eb37a1b27b6caf57b1aeae5e
5960,EPPGWIOF,brprintconflsr3,6594cac08d03782ad43d6b293faff904f20032c8eb37a1b27b6caf57b1aeae5e
5962,EPPGWIOF,rawtobr3,64efda7704564dd50c7514e74ef3c5252bc68af8f3b0d92358b64771980665af
6104,EPPGWIOF,rawtobr3,64efda7704564dd50c7514e74ef3c5252bc68af8f3b0d92358b64771980665af
6110,EPPGWIOF,brprintconflsr3,6594cac08d03782ad43d6b293faff904f20032c8eb37a1b27b6caf57b1aeae5e
6145,EPPGWIOF,brprintconflsr3,6594cac08d03782ad43d6b293faff904f20032c8eb37a1b27b6caf57b1aeae5e
6146,EPPGWIOF,rawtobr3,64efda7704564dd50c7514e74ef3c5252bc68af8f3b0d92358b64771980665af
6190,EPQKOBYG,win-lbp623-621-fw-v1301(1).exe,f475a7462dd85932ad7f99354751663d1543adb5e37c7c51ece78e10b6c37189
6369,EPPGWIOF,rawtobr3,64efda7704564dd50c7514e74ef3c5252bc68af8f3b0d92358b64771980665af
8169,EPEEHWSG,Library Books.xlsx,98d119993c27068f00bdf18a17d6613ae6ce6046b6b6620979282c2662c4efbd
9245,EPGSQVEB,Final_Documents.zip,404ee57531c33156d62154f49e3700c8c1f09cd0c75692f795748d59b9145088
9274,EP4YIFHV,bnpl.bundle.js,620389d26167bea08e56a90480f74d3dbd32c3e974f4de7a950953663a3fe6a1
9275,EP4YIFHV,bnpl_driver.js,6c21396c9518fa414ddb4dada2adb09e2d2b2fc5069d89da7e9df2adf2d95287
9282,EP4YIFHV,shopping_iframe_driver.js,100d970fc784e9bcb37b707ec4ef69825b165a073659f4068070a165184a087f
9283,EP4YIFHV,notification_fast.bundle.js,876ede3dba963ec8e7b99252979f3825807187785abb3759b99e3d35e30693fd
9284,EP4YIFHV,load-hub-i18n.bundle.js,036965c24ac54284e0bfac480395c91214e7b3c64d00215266a75e8977140f10
9285,EP4YIFHV,wallet_donation_driver.js,528c866fabbe17c30e9790a12ac09b94dd820ba4e46b0f9d9bb78a2795992f1c
9286,EP4YIFHV,edge_driver.js,985d0862ba672e36839438e44cbaf6d18537b53010b778a94bd7d7f2fa85af13
9302,EP4YIFHV,wallet_donation_driver.js,528c866fabbe17c30e9790a12ac09b94dd820ba4e46b0f9d9bb78a2795992f1c
9315,EP4YIFHV,c3f9c4a416e9e493005fc3f97adacbcf12956a81cc6c645d255fd023442c8120,c3f9c4a416e9e493005fc3f97adacbcf12956a81cc6c645d255fd023442c8120
9316,EP4YIFHV,webui-setup.js,e3d95016d065059105580ae8ba811cf4bb130b515b8c77e5e58cf95763ad938a
9317,EP4YIFHV,wallet-buynow.bundle.js,4aab5c4ac7a5cf0aab311362514cda20a2f3beb777a553756bf8ad8c7dfaa2bd
9318,EP4YIFHV,notification.bundle.js,b5aa710d917ed708f370fe187bbc5fc452e3bb66af0ed4f642e54cd155e86524

In [40]:
unique_artifacts = (
    malicious_clean[
        ["endpoint_id", "file_name", "sha256"]
    ]
    .drop_duplicates()
    .copy()
)

print("Unique endpoint/file/hash combinations:",
      len(unique_artifacts))

Unique endpoint/file/hash combinations: 51

In [41]:
display(
    unique_artifacts.sort_values(
        ["endpoint_id", "file_name"]
    ).head(50)
)

,endpoint_id,file_name,sha256
9326,EP4YIFHV,app-setup.js,d604ac767e070cf98b235b0281ef932c463fa11bceaf2fbf743bbf33743b0af1
9274,EP4YIFHV,bnpl.bundle.js,620389d26167bea08e56a90480f74d3dbd32c3e974f4de7a950953663a3fe6a1
9275,EP4YIFHV,bnpl_driver.js,6c21396c9518fa414ddb4dada2adb09e2d2b2fc5069d89da7e9df2adf2d95287
9323,EP4YIFHV,buynow_driver.js,bee346d14d293f9f4b989362041875b0257477a77759855e41c2f3cd40a6bed2
9315,EP4YIFHV,c3f9c4a416e9e493005fc3f97adacbcf12956a81cc6c645d255fd023442c8120,c3f9c4a416e9e493005fc3f97adacbcf12956a81cc6c645d255fd023442c8120
9320,EP4YIFHV,crypto.bundle.js,8e661de94430dc0293ca7964f0f9b89682e8fd2f56c17fb4b3c3de242d4f58d0
9286,EP4YIFHV,edge_driver.js,985d0862ba672e36839438e44cbaf6d18537b53010b778a94bd7d7f2fa85af13
9324,EP4YIFHV,load-ec-deps.bundle.js,f2bf148b4d999cb41ec764960ee718e0c9986a749f3b7be372ad86cf98f323de
9325,EP4YIFHV,load-ec-i18n.bundle.js,56bada50510d97878d514009279c3a662d9894a21c344fea8f9f9c5e3094614f
9284,EP4YIFHV,load-hub-i18n.bundle.js,036965c24ac54284e0bfac480395c91214e7b3c64d00215266a75e8977140f10
9327,EP4YIFHV,miniwallet.bundle.js,6f47d71e9ee52102a57e892441333ce18f60ba3e356c565b4742ff12e465234a
9318,EP4YIFHV,notification.bundle.js,b5aa710d917ed708f370fe187bbc5fc452e3bb66af0ed4f642e54cd155e86524
9283,EP4YIFHV,notification_fast.bundle.js,876ede3dba963ec8e7b99252979f3825807187785abb3759b99e3d35e30693fd
9321,EP4YIFHV,runtime.bundle.js,569e425e7f048b1f769c22d65aa91427b69c3d248068af5e628cd9467ef250ca
9282,EP4YIFHV,shopping_iframe_driver.js,100d970fc784e9bcb37b707ec4ef69825b165a073659f4068070a165184a087f
9322,EP4YIFHV,tokenized-card.bundle.js,39f5d83d7982cfae057053b0dcffa66fca12bee9769b1587a27e4387f56f29ec
9317,EP4YIFHV,wallet-buynow.bundle.js,4aab5c4ac7a5cf0aab311362514cda20a2f3beb777a553756bf8ad8c7dfaa2bd
9319,EP4YIFHV,wallet_checkout_autofill_driver.js,444d4db051edabd5abb29d93dcc5b07e0c662b03e2d785e4a28dfb7fc8032fc4
9285,EP4YIFHV,wallet_donation_driver.js,528c866fabbe17c30e9790a12ac09b94dd820ba4e46b0f9d9bb78a2795992f1c
9316,EP4YIFHV,webui-setup.js,e3d95016d065059105580ae8ba811cf4bb130b515b8c77e5e58cf95763ad938a
23430,EP7UYCXM,libeToken.so.10.7.77,574564cd6ed90f7938ab4967d5802f28cddc38ed1148e42838083ea6553c3be5
2997,EPAGTKNF,"Buy CP PLUS Dashboard Camera, Warranty NONE 1 year online _ Public Procurement Portal (PPP).pdf",18866b6f7308f73bc1b63193e50629bfd4fff701d6b9d3d2d6331b90e9162208
15257,EPAJI3E5,Lakeside traders.docx,c11e86d9e30b5fad8daf1c15c4dbbfd8d31b581a5d930b9c66d996d3bda11a2f
15258,EPAJI3E5,Lakeside traders.pdf,da22b024b1ba07c367e812e3c2f889f60cd3eb9758be906f6d5c231b8b71937b
8169,EPEEHWSG,Library Books.xlsx,98d119993c27068f00bdf18a17d6613ae6ce6046b6b6620979282c2662c4efbd
9245,EPGSQVEB,Final_Documents.zip,404ee57531c33156d62154f49e3700c8c1f09cd0c75692f795748d59b9145088
4999,EPJ42VCZ,RAGHAV STNA STNB.pdf,854b8f7716627df333e8ecfeae5887c02b3195658f7394573fe21b67e93e11be
4998,EPJ42VCZ,RAGHAV STNC STNA.pdf,a2beca1870ae689f4b046a20c3d8e2e48557d782dea53489b21a8b0adcef38be
11818,EPJ76RZV,COMPRESSED FINAL COMPARISION RETIREES WELFARE1.xlsx,d4a23078663777e758c04d2670b0d6aac8aa7ba5f91f811c5d94fa6ce8b7ef56
11182,EPMVZYZO,mydoc-10.pdf,5b7914202b30fc7e28ddcd2f82502aa8531035b812ee2194d978b7e920f43066
11191,EPMVZYZO,mydoc-75.pdf,92e24303edb5f2b6f1bc6c0c375655717eb2227c1622c4a723791aafce33965d
11192,EPMVZYZO,mydoc-9.pdf,7c10f54076fba8141f8ef95a701d0a4bdadfc63a5b98bec16b6b68439ebc3dc7
11193,EPMVZYZO,mydoc.pdf,d474833503a6404b8106d981c9f0769e4bd97033f45cf424e360b61f659c8cb1
18282,EPNPX6VY,Microsoft.Practices.EnterpriseLibrary.Common.dll,bde5bba12f076659ab19d3df625dedc7211180038c821b77b431b62647ef231f
5596,EPPGWIOF,brprintconflsr3,6594cac08d03782ad43d6b293faff904f20032c8eb37a1b27b6caf57b1aeae5e
5607,EPPGWIOF,rawtobr3,64efda7704564dd50c7514e74ef3c5252bc68af8f3b0d92358b64771980665af
21218,EPQBJBDX,dash cam.pdf,30c78bc9ec28a6e4d47708c309f8c88599c71a0fb379a3b4d75847d0f66ef0ca
6190,EPQKOBYG,win-lbp623-621-fw-v1301(1).exe,f475a7462dd85932ad7f99354751663d1543adb5e37c7c51ece78e10b6c37189
10895,EPRD7FJT,12th Plan Works Dashboard.pdf,5c7fc859c5a8f2bba02446c30020bb2b478686d66b566818c7382c840d95720f
18837,EPSES7ZK,hp_LJ1020_Full_Solution-v2012_918_1_57980(1).exe,f0c485571570100898f2d15531fbe4531ba303a252cd40a79b64c1976a5a9890
18844,EPSES7ZK,hp_LJ1020_Full_Solution-v2012_918_1_57980(2).exe,f0c485571570100898f2d15531fbe4531ba303a252cd40a79b64c1976a5a9890
18838,EPSES7ZK,hp_LJ1020_Full_Solution-v2012_918_1_57980(3).exe,f0c485571570100898f2d15531fbe4531ba303a252cd40a79b64c1976a5a9890
18848,EPSES7ZK,hp_LJ1020_Full_Solution-v2012_918_1_57980(4).exe,f0c485571570100898f2d15531fbe4531ba303a252cd40a79b64c1976a5a9890
18845,EPSES7ZK,hp_LJ1020_Full_Solution-v2012_918_1_57980.exe,f0c485571570100898f2d15531fbe4531ba303a252cd40a79b64c1976a5a9890
23163,EPSJWX5J,Staff_Library_Payment_Final.docx,d831cf990c1445b507ef9fea05a6e483983aa4737fa56fcf650a96af1cee0cd5
9331,EPT3KTUL,Dash Camera-49600.00.pdf,7505de4759aadebf5e21b2cc0f7f13fccdbec968e3b82be70791197fac3d21bc
13095,EPVC2P55,Data1.cab,925b63ce20d94bc4a0d98d02d153161dbba9ac61c39ec323ac8a73b2acbde42e
21524,EPVSWBNA,Strings.dll,ae107170c153cb3eb34c049482722d3937f2c03a6c23cadb9bbdb9034e28b9c0
21525,EPVSWBNA,launcher.exe,61a67e53c6c0c80a4e95af35a2997ad2ce59720020fc7438991eda3541df73b6
21526,EPVSWBNA,zshp1020s.dll,c6525c5230387653e16f21f408eab8202157b0eddeb180bd91a13e860fbee4f4


## Malicious Security Telemetry

The endpoint-security dataset contains explicit security detections marked
`FileType: Malicious`. This section profiles those records before they are
represented in the endpoint–artifact graph.

This is detection evidence from the source telemetry. It should not by itself
be interpreted as proof that an endpoint was compromised or that a malicious
artifact was executed.

In [ ]:

# Load the endpoint-security source data independently so this profiling
# section remains reproducible even if earlier notebook cells are reordered.
from pathlib import Path
import pandas as pd

project_root = Path.cwd().parent
security_path = project_root / "data" / "endpoint_security.csv"

security_df = pd.read_csv(security_path)

# Restrict the analysis to records explicitly classified as malicious by the
# source security telemetry rather than inferring maliciousness from filenames.
malicious_security_df = security_df[
    security_df["message"]
    .fillna("")
    .str.contains(
        "FileType: Malicious",
        case=False,
        na=False
    )
].copy()

print(f"Security records: {len(security_df):,}")
print(f"Explicit malicious records: {len(malicious_security_df):,}")
print(
    "Endpoints with explicit malicious telemetry:",
    malicious_security_df["endpoint_id"].nunique()
)

display(
    malicious_security_df[
        [
            "endpoint_id",
            "event_time",
            "message"
        ]
    ].head(10)
)

In [3]:
# Load the complete raw endpoint-security dataset independently of the
# malicious-only artifact investigation scope.
raw_security = pd.read_csv("../data/endpoint_security.csv")

# Identify every endpoint present in the complete raw telemetry.
all_endpoints = sorted(
    raw_security["endpoint_id"]
    .dropna()
    .unique()
)

# Identify endpoints with at least one explicit FileType: Malicious record.
malicious_records = raw_security[
    raw_security["message"]
    .fillna("")
    .str.contains(
        "FileType: Malicious",
        case=False,
        na=False,
    )
]

malicious_endpoints = sorted(
    malicious_records["endpoint_id"]
    .dropna()
    .unique()
)

# Identify endpoints present in the raw data but without an explicit
# malicious security detection.
non_malicious_endpoints = sorted(
    set(all_endpoints) - set(malicious_endpoints)
)

print("=" * 60)
print("RAW DATASET ENDPOINT VERIFICATION")
print("=" * 60)

print(f"Total endpoints in raw dataset: {len(all_endpoints)}")
print(
    f"Endpoints with explicit malicious detections: "
    f"{len(malicious_endpoints)}"
)
print(
    f"Endpoints without explicit malicious detections: "
    f"{len(non_malicious_endpoints)}"
)

print("\nAll endpoints:")
print(all_endpoints)

print("\nEndpoints with explicit malicious detections:")
print(malicious_endpoints)

print("\nEndpoints without explicit malicious detections:")
print(non_malicious_endpoints)

============================================================
RAW DATASET ENDPOINT VERIFICATION
============================================================
Total endpoints in raw dataset: 247
Endpoints with explicit malicious detections: 33
Endpoints without explicit malicious detections: 214

All endpoints:
['EP2C4ZH5', 'EP2EVFKU', 'EP2SJ6NE', 'EP2YUIUX', 'EP3GALVS', 'EP3JZO7Y', 'EP3PJJZF', 'EP3SKSVQ', 'EP3XZALW', 'EP3Z5SXV', 'EP3ZPBUE', 'EP4C4STG', 'EP4HZ33W', 'EP4MZIBL', 'EP4PGHIT', 'EP4RS3P7', 'EP4WW2QO', 'EP4YIFHV', 'EP55ZUGP', 'EP5DHOIP', 'EP5JYWEZ', 'EP5KBVLG', 'EP5NU2IP', 'EP5U5X2I', 'EP63QFAS', 'EP65VPYQ', 'EP67QOYP', 'EP6D7K7J', 'EP6HECD2', 'EP6IKT5R', 'EP6RMQC5', 'EP6SCJIM', 'EP6TZCQ6', 'EP6WDXYR', 'EP6WOB2Q', 'EP7FLWZB', 'EP7FZ2XY', 'EP7OWDTR', 'EP7PCCYI', 'EP7UYCXM', 'EP7XJK3C', 'EPADG3JU', 'EPAGTKNF', 'EPAJI3E5', 'EPALDFJP', 'EPAM6DF7', 'EPAPPPPN', 'EPAR5TSH', 'EPARWEH7', 'EPAX5P5D', 'EPB5VWOI', 'EPB7PFDD', 'EPBG5SVE', 'EPBIBHNA', 'EPBIT7ZS', 'EPBMNHPG', 'EPBMNRN7', 'EPBUUL45', 'EPBVEPUN', 'EPBWRBCV', 'EPBZVWPM', 'EPC2L3UH', 'EPC7TXDE', 'EPCKIU6N', 'EPCLJGKA', 'EPCPSGXR', 'EPCQBKSG', 'EPCRFN4D', 'EPD3I3JF', 'EPD7B7DQ', 'EPDO62BH', 'EPDR3POY', 'EPDRB236', 'EPDVCZ3P', 'EPDYIGF3', 'EPE4RO5I', 'EPE556O2', 'EPE7YMMO', 'EPEEHWSG', 'EPELOQ73', 'EPEPTYRN', 'EPEWYRFX', 'EPF4AJCM', 'EPF5L3TA', 'EPFE66OS', 'EPFF7UHG', 'EPFFTO5T', 'EPFQEJS4', 'EPFQSCDV', 'EPFV5FDB', 'EPFYWUMZ', 'EPG52BAX', 'EPG67237', 'EPGBKH56', 'EPGHGYUU', 'EPGHTVEF', 'EPGJZAX6', 'EPGN44A5', 'EPGPX2E7', 'EPGQPYHM', 'EPGSQVEB', 'EPGW2NY4', 'EPH5P2EZ', 'EPHBRTQ2', 'EPHFTD5E', 'EPHR4FSL', 'EPHXCFTB', 'EPHXH7MS', 'EPI5GLUK', 'EPIBYMGG', 'EPIE7YGU', 'EPIEJIZC', 'EPIEVJCR', 'EPIHPLA2', 'EPIL2MXD', 'EPIXXNDT', 'EPIZFLLQ', 'EPJ42VCZ', 'EPJ76RZV', 'EPJ7BIHC', 'EPJBGHPZ', 'EPJCQSGS', 'EPJJXRUF', 'EPJLQHJM', 'EPJRQKEK', 'EPJRRWOP', 'EPJTXZSB', 'EPJYEC7F', 'EPKBJO66', 'EPKJTRB2', 'EPKTB5NE', 'EPKYLAT4', 'EPKYURHG', 'EPL4KXNW', 'EPL63W52', 'EPL7JJQY', 'EPLDM6PE', 'EPLFOXSS', 'EPLHBJHI', 'EPLKONPA', 'EPLWNRA5', 'EPLZ6PWJ', 'EPM4M3ZE', 'EPMDU6L5', 'EPME77ML', 'EPMINU2I', 'EPMQTKSL', 'EPMUW4SM', 'EPMVZYZO', 'EPMY53PL', 'EPN2FFTL', 'EPN6LGXP', 'EPNCY7H3', 'EPNGOVPF', 'EPNME2LP', 'EPNPX6VY', 'EPNWM26Q', 'EPNXD2NI', 'EPNZ47AH', 'EPO7DU5Z', 'EPOC6Y4R', 'EPPGWIOF', 'EPPI5OVD', 'EPPJ5DMQ', 'EPPQ2PVU', 'EPPTT5KU', 'EPPWQND4', 'EPPXBL74', 'EPQ3UAYV', 'EPQ6H57A', 'EPQ6OARX', 'EPQA4SVZ', 'EPQBJBDX', 'EPQEM443', 'EPQHPXVS', 'EPQISSR3', 'EPQISY6K', 'EPQIWPBQ', 'EPQKOBYG', 'EPQMSMUV', 'EPQOEF4W', 'EPQPZCCJ', 'EPQTJPGC', 'EPR3CJU6', 'EPR4BEDS', 'EPR6HUBY', 'EPRD7FJT', 'EPROB4NT', 'EPRWDOV2', 'EPRYJZPO', 'EPRZ27TP', 'EPSES7ZK', 'EPSJWX5J', 'EPSMPJ6E', 'EPSRNMSV', 'EPSUHSD5', 'EPT3KTUL', 'EPT4VYZW', 'EPT7QLXR', 'EPTAGDTB', 'EPTDOI6T', 'EPTMFZSX', 'EPTVIEOE', 'EPTX4FCZ', 'EPU5M2ZB', 'EPUJL36T', 'EPUO3HHV', 'EPUP42UF', 'EPURTVI7', 'EPUTB7FS', 'EPUTH546', 'EPUVWNDY', 'EPUWQP4P', 'EPV25MPO', 'EPV7MB2K', 'EPVC2P55', 'EPVEKWWM', 'EPVOVTRD', 'EPVSWBNA', 'EPVTGUK4', 'EPVU2V5T', 'EPWADX3W', 'EPWEVZJP', 'EPWGE25U', 'EPWHYCYU', 'EPWNKSRM', 'EPWZ7L6L', 'EPX6YJD7', 'EPXHJLGU', 'EPXKHG4K', 'EPXQDYTY', 'EPXVUZL4', 'EPXWWCE7', 'EPXXUZPL', 'EPY2ASSU', 'EPYG5XQP', 'EPYJFFRM', 'EPYLSVPL', 'EPYRW5CW', 'EPYXIF66', 'EPZ4RN7K', 'EPZETVZS', 'EPZJCG3R', 'EPZL6TNQ', 'EPZOABKY', 'EPZQDT6J', 'EPZRAPEL']

Endpoints with explicit malicious detections:
['EP2SJ6NE', 'EP3GALVS', 'EP4YIFHV', 'EP7UYCXM', 'EPAGTKNF', 'EPAJI3E5', 'EPC2L3UH', 'EPDRB236', 'EPEEHWSG', 'EPF4AJCM', 'EPFQSCDV', 'EPGSQVEB', 'EPJ42VCZ', 'EPJ76RZV', 'EPJYEC7F', 'EPLDM6PE', 'EPMDU6L5', 'EPMQTKSL', 'EPMVZYZO', 'EPNPX6VY', 'EPOC6Y4R', 'EPPGWIOF', 'EPQBJBDX', 'EPQKOBYG', 'EPR4BEDS', 'EPRD7FJT', 'EPSES7ZK', 'EPSJWX5J', 'EPT3KTUL', 'EPVC2P55', 'EPVSWBNA', 'EPWZ7L6L', 'EPZRAPEL']

Endpoints without explicit malicious detections:
['EP2C4ZH5', 'EP2EVFKU', 'EP2YUIUX', 'EP3JZO7Y', 'EP3PJJZF', 'EP3SKSVQ', 'EP3XZALW', 'EP3Z5SXV', 'EP3ZPBUE', 'EP4C4STG', 'EP4HZ33W', 'EP4MZIBL', 'EP4PGHIT', 'EP4RS3P7', 'EP4WW2QO', 'EP55ZUGP', 'EP5DHOIP', 'EP5JYWEZ', 'EP5KBVLG', 'EP5NU2IP', 'EP5U5X2I', 'EP63QFAS', 'EP65VPYQ', 'EP67QOYP', 'EP6D7K7J', 'EP6HECD2', 'EP6IKT5R', 'EP6RMQC5', 'EP6SCJIM', 'EP6TZCQ6', 'EP6WDXYR', 'EP6WOB2Q', 'EP7FLWZB', 'EP7FZ2XY', 'EP7OWDTR', 'EP7PCCYI', 'EP7XJK3C', 'EPADG3JU', 'EPALDFJP', 'EPAM6DF7', 'EPAPPPPN', 'EPAR5TSH', 'EPARWEH7', 'EPAX5P5D', 'EPB5VWOI', 'EPB7PFDD', 'EPBG5SVE', 'EPBIBHNA', 'EPBIT7ZS', 'EPBMNHPG', 'EPBMNRN7', 'EPBUUL45', 'EPBVEPUN', 'EPBWRBCV', 'EPBZVWPM', 'EPC7TXDE', 'EPCKIU6N', 'EPCLJGKA', 'EPCPSGXR', 'EPCQBKSG', 'EPCRFN4D', 'EPD3I3JF', 'EPD7B7DQ', 'EPDO62BH', 'EPDR3POY', 'EPDVCZ3P', 'EPDYIGF3', 'EPE4RO5I', 'EPE556O2', 'EPE7YMMO', 'EPELOQ73', 'EPEPTYRN', 'EPEWYRFX', 'EPF5L3TA', 'EPFE66OS', 'EPFF7UHG', 'EPFFTO5T', 'EPFQEJS4', 'EPFV5FDB', 'EPFYWUMZ', 'EPG52BAX', 'EPG67237', 'EPGBKH56', 'EPGHGYUU', 'EPGHTVEF', 'EPGJZAX6', 'EPGN44A5', 'EPGPX2E7', 'EPGQPYHM', 'EPGW2NY4', 'EPH5P2EZ', 'EPHBRTQ2', 'EPHFTD5E', 'EPHR4FSL', 'EPHXCFTB', 'EPHXH7MS', 'EPI5GLUK', 'EPIBYMGG', 'EPIE7YGU', 'EPIEJIZC', 'EPIEVJCR', 'EPIHPLA2', 'EPIL2MXD', 'EPIXXNDT', 'EPIZFLLQ', 'EPJ7BIHC', 'EPJBGHPZ', 'EPJCQSGS', 'EPJJXRUF', 'EPJLQHJM', 'EPJRQKEK', 'EPJRRWOP', 'EPJTXZSB', 'EPKBJO66', 'EPKJTRB2', 'EPKTB5NE', 'EPKYLAT4', 'EPKYURHG', 'EPL4KXNW', 'EPL63W52', 'EPL7JJQY', 'EPLFOXSS', 'EPLHBJHI', 'EPLKONPA', 'EPLWNRA5', 'EPLZ6PWJ', 'EPM4M3ZE', 'EPME77ML', 'EPMINU2I', 'EPMUW4SM', 'EPMY53PL', 'EPN2FFTL', 'EPN6LGXP', 'EPNCY7H3', 'EPNGOVPF', 'EPNME2LP', 'EPNWM26Q', 'EPNXD2NI', 'EPNZ47AH', 'EPO7DU5Z', 'EPPI5OVD', 'EPPJ5DMQ', 'EPPQ2PVU', 'EPPTT5KU', 'EPPWQND4', 'EPPXBL74', 'EPQ3UAYV', 'EPQ6H57A', 'EPQ6OARX', 'EPQA4SVZ', 'EPQEM443', 'EPQHPXVS', 'EPQISSR3', 'EPQISY6K', 'EPQIWPBQ', 'EPQMSMUV', 'EPQOEF4W', 'EPQPZCCJ', 'EPQTJPGC', 'EPR3CJU6', 'EPR6HUBY', 'EPROB4NT', 'EPRWDOV2', 'EPRYJZPO', 'EPRZ27TP', 'EPSMPJ6E', 'EPSRNMSV', 'EPSUHSD5', 'EPT4VYZW', 'EPT7QLXR', 'EPTAGDTB', 'EPTDOI6T', 'EPTMFZSX', 'EPTVIEOE', 'EPTX4FCZ', 'EPU5M2ZB', 'EPUJL36T', 'EPUO3HHV', 'EPUP42UF', 'EPURTVI7', 'EPUTB7FS', 'EPUTH546', 'EPUVWNDY', 'EPUWQP4P', 'EPV25MPO', 'EPV7MB2K', 'EPVEKWWM', 'EPVOVTRD', 'EPVTGUK4', 'EPVU2V5T', 'EPWADX3W', 'EPWEVZJP', 'EPWGE25U', 'EPWHYCYU', 'EPWNKSRM', 'EPX6YJD7', 'EPXHJLGU', 'EPXKHG4K', 'EPXQDYTY', 'EPXVUZL4', 'EPXWWCE7', 'EPXXUZPL', 'EPY2ASSU', 'EPYG5XQP', 'EPYJFFRM', 'EPYLSVPL', 'EPYRW5CW', 'EPYXIF66', 'EPZ4RN7K', 'EPZETVZS', 'EPZJCG3R', 'EPZL6TNQ', 'EPZOABKY', 'EPZQDT6J']